// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dwell_time_
std::vector < bool > dwell_time_(std::list < std::vector < int > > timestamps, int dwell_value);
RcppExport SEXP ortiz_dwell_time_(SEXP timestampsSEXP, SEXP dwell_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::list < std::vector < int > > >::type timestamps(timestampsSEXP);
    Rcpp::traits::input_parameter< int >::type dwell_value(dwell_valueSEXP);
    __result = Rcpp::wrap(dwell_time_(timestamps, dwell_value));
    return __result;
END_RCPP
}
