// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dwell_time_
std::vector < unsigned int > dwell_time_(std::list < std::vector < int > > timestamps);
RcppExport SEXP ortiz_dwell_time_(SEXP timestampsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::list < std::vector < int > > >::type timestamps(timestampsSEXP);
    __result = Rcpp::wrap(dwell_time_(timestamps));
    return __result;
END_RCPP
}
