// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dwell_time_
std::vector < unsigned int > dwell_time_(std::list < std::vector < int > > timestamps);
RcppExport SEXP ortiz_dwell_time_(SEXP timestampsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::list < std::vector < int > > >::type timestamps(timestampsSEXP);
    rcpp_result_gen = Rcpp::wrap(dwell_time_(timestamps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"ortiz_dwell_time_", (DL_FUNC) &ortiz_dwell_time_, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_ortiz(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
